 export var dayToSchedule = {                
      "Sunday": "No School",
      "Monday": "Normal",
      "Tuesday": "Normal",
      "Wednesday": "Normal",
      "Thursday": "Normal",
      "Friday": "Normal",
      "Saturday": "No School"
    }

export var ignoredPeriods = [
                      "No School",
                      "Before School",
                      "Warning Bell",
                      "Passing Time",
                     ];

export var schedule = {
    "No School" : [
          {name: "No School", start: "12:00a", end: "12:00a"}
         ], 
    "Normal": [
           {name: "Before School", start: "7:05a", end: "7:50a"},
           {name: "Warning Bell", start: "7:50a", end: "7:55a"},
           {name: "Period 1", start: "7:55a", end: "8:44a"},
           {name: "Passing Time", start: "8:44a", end: "8:47a"},
           {name: "Period 2", start: "8:47a", end: "9:34a"}, 
           {name: "Passing Time", start: "9:34a", end: "9:37a"},
           {name: "Period 3", start: "9:37a", end: "10:17a"},
           {name: "Passing Time", start: "10:17a", end: "10:20a"},
           {name: "Period 4", start: "10:20a", end: "11:07a"}, 
           {name: "Passing Time", start: "11:07a", end: "11:10a"},
           {name: "Period 5", start: "11:10a", end: "11:45a"},
           {name: "Passing Time", start: "11:45a", end: "11:48pa"},
           {name: "Period 6", start: "11:48a", end: "12:35p"},
           {name: "Passing Time", start: "12:35p", end: "12:38p"},
           {name: "Period 7", start: "12:38p", end: "1:25p"},
           {name: "Passing Time", start: "1:25p", end: "1:28p"},
           {name: "Period 8", start: "1:28p", end: "2:15p"},
           {name: "Passing Time", start: "2:15p", end: "2:18p"},
           {name: "Period 9", start: "2:18p", end: "3:05p"},
          ],
    "2 Hour Delay": [
           {name: "Before School", start: "7:05a", end: "7:50a"},
           {name: "Warning Bell", start: "7:50a", end: "7:55a"},
           {name: "Period 1", start: "7:55a", end: "8:44a"},
           {name: "Passing Time", start: "8:44a", end: "8:47a"},
           {name: "Period 2", start: "8:47a", end: "9:34a"}, 
           {name: "Passing Time", start: "9:34a", end: "9:37a"},
           {name: "Period 3", start: "9:37a", end: "10:17a"},
           {name: "Passing Time", start: "10:17a", end: "10:20a"},
           {name: "Period 4", start: "10:20a", end: "11:07a"}, 
           {name: "Passing Time", start: "11:07a", end: "11:10a"},
           {name: "Period 5", start: "11:10a", end: "11:45a"},
           {name: "Passing Time", start: "11:45a", end: "11:48pa"},
           {name: "Period 6", start: "11:48a", end: "12:35p"},
           {name: "Passing Time", start: "12:35p", end: "12:38p"},
           {name: "Period 7", start: "12:38p", end: "1:25p"},
           {name: "Passing Time", start: "1:25p", end: "1:28p"},
           {name: "Period 8", start: "1:28p", end: "2:15p"},
           {name: "Passing Time", start: "2:15p", end: "2:18p"},
           {name: "Period 9", start: "2:18p", end: "3:05p"},
          ],
    "Student Council #1": [
           {name: "Before School", start: "7:05a", end: "7:50a"},
           {name: "Warning Bell", start: "7:50a", end: "7:55a"},
           {name: "Period 1", start: "7:55a", end: "8:33a"},
           {name: "Passing Time", start: "8:33a", end: "8:36a"},
           {name: "Period 2", start: "8:36a", end: "9:11a"}, 
           {name: "Passing Time", start: "9:11a", end: "9:14a"},
           {name: "Period 4", start: "9:14a", end: "9:49a"},
           {name: "Passing Time", start: "9:49a", end: "9:52a"},
           {name: "Period 5/6", start: "9:52a", end: "10:27a"}, 
           {name: "Passing Time", start: "10:27a", end: "10:30a"},
           {name: "Period 7", start: "10:30a", end: "11:05a"},
           {name: "Passing Time", start: "11:05a", end: "11:08pa"},
           {name: "Period 8", start: "10:30a", end: "11:43a"},
           {name: "Passing Time", start: "11:43a", end: "11:46a"},
           {name: "Lunch", start: "11:46a", end: "12:31p"},
           {name: "Passing Time", start: "12:31p", end: "12:34p"},
           {name: "Period 9", start: "12:34p", end: "1:09p"},
          ],
};

